export const Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: '',
          full_name: '',
          avatar_url: null,
          title: null,
          company_id: null,
          graduation_year: null,
          department: null,
          bio: null,
          location: null,
          created_at: '',
          updated_at: '',
        },
        Insert: {
          id: '',
          full_name: '',
          avatar_url: null,
          title: null,
          company_id: null,
          graduation_year: null,
          department: null,
          bio: null,
          location: null,
          created_at: '',
          updated_at: '',
        },
        Update: {
          id: '',
          full_name: '',
          avatar_url: null,
          title: null,
          company_id: null,
          graduation_year: null,
          department: null,
          bio: null,
          location: null,
          created_at: '',
          updated_at: '',
        },
      },
      companies: {
        Row: {
          id: '',
          name: '',
          logo_url: null,
          website: null,
          description: null,
          created_at: '',
        },
        Insert: {
          id: '',
          name: '',
          logo_url: null,
          website: null,
          description: null,
          created_at: '',
        },
        Update: {
          id: '',
          name: '',
          logo_url: null,
          website: null,
          description: null,
          created_at: '',
        },
      },
      jobs: {
        Row: {
          id: '',
          title: '',
          company_id: '',
          location: null,
          description: null,
          requirements: [],
          posted_by: '',
          type: null,
          status: '',
          created_at: '',
          updated_at: '',
        },
        Insert: {
          id: '',
          title: '',
          company_id: '',
          location: null,
          description: null,
          requirements: [],
          posted_by: '',
          type: null,
          status: '',
          created_at: '',
          updated_at: '',
        },
        Update: {
          id: '',
          title: '',
          company_id: '',
          location: null,
          description: null,
          requirements: [],
          posted_by: '',
          type: null,
          status: '',
          created_at: '',
          updated_at: '',
        },
      },
      events: {
        Row: {
          id: '',
          title: '',
          description: null,
          event_date: '',
          location: null,
          type: null,
          organizer_id: '',
          max_participants: null,
          created_at: '',
        },
        Insert: {
          id: '',
          title: '',
          description: null,
          event_date: '',
          location: null,
          type: null,
          organizer_id: '',
          max_participants: null,
          created_at: '',
        },
        Update: {
          id: '',
          title: '',
          description: null,
          event_date: '',
          location: null,
          type: null,
          organizer_id: '',
          max_participants: null,
          created_at: '',
        },
      },
    },
  },
};
